.eslintrc.js
.gitignore
.prettierrc
Dockerfile
Jenkinsfile
README.md
docker-compose.yml
nest-cli.json
package.json
src/app.controller.spec.ts
src/app.controller.ts
src/app.module.ts
src/app.service.ts
src/main.ts
test/app.e2e-spec.ts
test/jest-e2e.json
tsconfig.build.json
tsconfig.json

Nest 초기세팅 및 DockerFile, JenkinsFile 설정
<br><br>
Nest 초기세팅 및 DockerFile, JenkinsFile 설정
<br><br>
<br><br>
- issue: SCRUM-91
<br><br>

set: Nest 초기세팅 및 DockerFile, JenkinsFile 설정 issue: SCRUM-91

---

Dockerfile.test

<br><br>
<br><br>
<br><br>
- Close #이슈번호
<br><br>

add: Dockerfile.test

---

Jenkinsfile

- jenkins pipeline 수정
<br><br>
- eslint 실행 스크립트 추가
-  jest 테스트 실행 스크립트 추가
<br><br>
- issue: SCRUM-96
<br><br>

set: jenkins pipeline 수정

---

docker-compose.yml
package.json
src/app.module.ts
src/auth/auth.module.ts
src/auth/auth.service.ts
src/auth/jwt.guard.ts
src/auth/test/auth.service.spec.ts
src/global/common/validation/ParseJsonAndValidatePipe.ts
src/global/exception/custom.exception.ts
src/global/exception/global-exception.filter.ts
src/global/redis/redis.module.ts
src/modules/projectTeams/repository/projectTeam.repository.ts
src/modules/resumes/repository/resume.repository.ts
src/modules/resumes/resume.module.ts
src/modules/resumes/resume.service.ts
src/modules/resumes/test/resume.service.spec.ts
src/modules/studyTeams/repository/studyTeam.repository.ts
src/modules/studyTeams/studyTeam.controller.ts
src/modules/studyTeams/test/mock-data.ts
src/modules/studyTeams/test/studyTeam.repository.spec.ts
src/modules/users/dto/request/create.user.request.ts
src/modules/users/repository/user.repository.ts
src/modules/users/test/user.controller.spec.ts
src/modules/users/test/user.service.spec.ts
src/modules/users/user.controller.ts
src/modules/users/user.module.ts
src/modules/users/user.service.ts

- 레디스 환경 변수 처리 수정
- 순환참조 해결
- 특정 스터디 모든 참여 인원 조회 반환값 리더 여부 추가 
- 회원가입 시 트랜잭션 처리 
- 이메일 인증 시 예외처리 추가(테커인지, 이미 가입한 유저인지 체크)
<br><br>
SCRUM-191
<br><br>

fix : 배포 오류 해결

---

src/main.ts

스웨거 주소 CORS 추가
SCRUM-191
<br><br>

fix: CORS 주소 추가 issue: SCRUM-191

---

docker-compose.yml
src/app.module.ts
src/googleDrive/google.drive.service.ts
src/modules/likes/dto/request/create.like.request.ts
src/modules/likes/dto/request/get.like.request.ts
src/modules/likes/dto/response/get.like.response.ts
src/modules/likes/like.controller.ts
src/modules/likes/like.module.ts
src/modules/likes/like.service.ts
src/modules/likes/repository/like.repository.ts
src/modules/likes/test/like.controller.spec.ts
src/modules/likes/test/like.repository.spec.ts
src/modules/likes/test/like.service.spec.ts
src/modules/likes/test/mock-data.ts
src/modules/resumes/resume.module.ts
src/modules/users/user.module.ts

좋아요 레디스 삭제
<br><br>
- 좋아요 기능에서 레디스를 사용한 캐싱 처리를 제거했습니다.
- 콘텐츠 존재 여부 조회와 좋아요 상태 업데이트, likeCount 업데이트를 트랜잭션 처리했습니다.
<br><br>
<br><br>
issue: SCRUM-192
<br><br>

fix: 좋아요 레디스 삭제

---

src/auth/auth.controller.ts
src/modules/users/test/user.controller.spec.ts
src/modules/users/user.controller.ts

반환값 수정했습니다.
<br><br>
SCRUM-203
<br><br>

fix : 반환값 수정(User, Auth) issue: SCRUM-203

---

src/modules/users/dto/response/get.user.response.ts
src/modules/users/repository/user.repository.ts

삭제된 사용자는 로그인 불가능하게 끔 수정
<br><br>
SCRUM-204
<br><br>

fix: 로그인 로직 수정 issue: SCRUM-204

---

src/modules/users/dto/response/get.user.response.ts

모든 프로필 조회 id 추가
SCRUM-204
<br><br>

fix: 반환값 추가 issue: SCRUM-204

---

src/auth/auth.controller.ts

서브 도메인 쿠키 공유 설정
SCRUM-207
<br><br>

fix: 서브 도메인 쿠키 공유 설정

---

.github/workflows/ci.yml

- 도커 이미지 latest및 arm64 지원
- ci.yml 수정
<br><br>
SCRUM-215
<br><br>

Scrum 215  fix cicd

---

src/global/exception/custom.exception.ts
src/modules/userExperiences/dto/request/update.experience.request.ts
src/modules/userExperiences/dto/request/update.userExperience.request.ts
src/modules/userExperiences/repository/userExperience.repository.ts
src/modules/users/repository/user.repository.ts
src/modules/users/user.controller.ts
src/modules/users/user.service.ts

- 경력 업데이트 로직 수정
- 경력 삭제 api 작업
<br><br>
<br><br>
<br><br>
SCRUM-222
<br><br>

feat: 업데이트 로직 수정 및 경력 삭제 API 작업 issue: SCRUM-222

---

.github/workflows/ci.yml

<br><br>
<br><br>
<br><br>
SCRUM-224
<br><br>

fix: CI 수정 issue: SCRUM-224

---

src/modules/sessions/dto/request/get.session.query.request.ts
src/modules/sessions/repository/session.repository.ts
src/modules/sessions/test/mock-data.ts
src/modules/sessions/test/session.repository.spec.ts

- 세션 목록 조회에서 키워드 삭제
<br><br>
<br><br>
<br><br>
66-fix
<br><br>

fix: 세션에서 키워드 삭제

---

src/modules/users/repository/user.repository.ts

<br><br>
<br><br>
<br><br>
SCRUM-226
<br><br>

fix: 기수 필터링 수정 issue: SCRUM-226

---

src/modules/stacks/dto/response/get.stack.response.ts
src/modules/stacks/repository/stack.repository.ts
src/modules/stacks/stack.controller.ts
src/modules/stacks/stack.service.ts
src/modules/stacks/test/mock-data.ts
src/modules/stacks/test/stack.controller.spec.ts
src/modules/stacks/test/stack.repository.spec.ts
src/modules/stacks/test/stack.servie.spec.ts

- 스택 조회 API 구현
<br><br>
<br><br>
<br><br>
68-feat
<br><br>

feat: 스택 조회 API 구현

---

prisma/migrations/20250220172759_fix_uiux_num/migration.sql

<br><br>
<br><br>
<br><br>
SCRUM-227
<br><br>

fix: 프리즈마 충돌 오류 해결

---

src/modules/studyTeams/dto/request/create.studyTeam.request.ts
src/modules/studyTeams/dto/response/get.studyTeam.response.ts
src/modules/studyTeams/repository/studyTeam.repository.ts
src/modules/studyTeams/studyTeam.controller.ts

<br><br>
<br><br>
<br><br>
SCRUM-
<br><br>

fix: 스터디 생성 프로필 이미지 추가

---

src/modules/users/dto/response/get.user.response.ts
src/modules/users/repository/user.repository.ts

<br><br>
<br><br>
<br><br>
SCRUM-
<br><br>

fix: 유저 조회 메인 이미지 반환값 추가

---

src/modules/studyTeams/studyTeam.controller.ts
src/modules/studyTeams/studyTeam.service.ts

<br><br>
<br><br>
<br><br>
SCRUM-
<br><br>

feat: 스터디 공고 생성 수정

---

src/modules/studyTeams/studyTeam.controller.ts

<br><br>
<br><br>
<br><br>
SCRUM-
<br><br>

feat: 로그 추가

---

src/modules/studyTeams/studyTeam.controller.ts

<br><br>
<br><br>
<br><br>
SCRUM-
<br><br>

feat: 로깅 추가

---

src/global/logger/winston.logger.ts

<br><br>
<br><br>
<br><br>
SCRUM-
<br><br>

feat: logger level 변경

---

src/modules/blogs/blog.controller.ts
src/modules/blogs/blog.service.ts
src/modules/blogs/repository/blog.repository.ts

<br><br>
블로그 삭제 구현완료 (soft delete)
<br><br>
<br><br>
SCRUM-231
<br><br>

feat: 블로그 삭제 구현완료

---

src/modules/projectTeams/projectTeam.service.ts
src/modules/studyMembers/repository/studyMember.repository.ts
src/modules/studyTeams/studyTeam.service.ts

<br><br>
<br><br>
<br><br>
SCRUM-
<br><br>

fix: 재신청 허용 로직 추가

---

src/modules/projectTeams/projectTeam.service.ts

<br><br>
<br><br>
<br><br>
SCRUM-
<br><br>

fix: 오름차순 반환으로 수정

---

src/modules/sessions/session.controller.ts

- 세션 API 토큰 추가
<br><br>
<br><br>
<br><br>
87-fix
<br><br>

fix: 세션 API 토큰 추가

---

src/modules/projectMembers/repository/projectMember.repository.ts
src/modules/projectTeams/dto/request/update.projectTeam.request.ts
src/modules/projectTeams/projectTeam.controller.ts
src/modules/projectTeams/projectTeam.service.ts
src/modules/studyMembers/repository/studyMember.repository.ts
src/modules/studyTeams/studyTeam.service.ts

<br><br>
지원자 수락시 모집 인원 줄이기
공고 생성, 조회할 때 오름차순으로 팀원 조회하게끔 수정
이미지 삭제 - "deleteMainImages":[1,2,3], "deleteResultImages":[1,2,3]
방식으로 수정
<br><br>
<br><br>
SCRUM-
<br><br>

fix: 프로젝트api  수정사항 반영

---

src/modules/projectTeams/projectTeam.service.ts

<br><br>
프로젝트  수정사항 반영 (update로직)
<br><br>
<br><br>
SCRUM-
<br><br>

fix: 프로젝트  수정사항 반영

---

src/modules/projectTeams/projectTeam.controller.ts
src/modules/projectTeams/projectTeam.service.ts
src/modules/studyTeams/studyTeam.controller.ts
src/modules/studyTeams/studyTeam.service.ts

<br><br>
프로젝트, 스터디 리더 1명은 무조건 있어야하게끔 수정
프로젝트 image 로직 수정
<br><br>
<br><br>
SCRUM-
<br><br>

fix: 프로젝트& 스터디 리더로직, image 로직 수정

---

src/global/index/index.service.ts
src/modules/blogs/repository/blog.repository.ts
src/modules/likes/repository/like.repository.ts
src/modules/projectTeams/projectTeam.service.ts
src/modules/sessions/session.service.ts

인덱스 추가 구현 (세션 조회, 좋아요 설정, 블로그 삭제 시)
<br><br>
- 세션 조회
- 세션 좋아요 설정 변경
- 블로그 삭제
위의 3가지 경우 인덱스 업데이트를 실행합니다.
<br><br>
<br><br>
SCRUM-237
<br><br>

feat: 인덱스 추가 구현 (세션 조회, 좋아요 설정, 블로그 삭제 시)

---

src/global/exception/custom.exception.ts
src/modules/projectTeams/projectTeam.controller.ts
src/modules/projectTeams/projectTeam.service.ts
src/modules/studyTeams/studyTeam.service.ts

<br><br>
프로젝트&스터디 생성시 리더 로직 수정
<br><br>
<br><br>
SCRUM-
<br><br>

fix: 프로젝트&스터디 생성시 리더 로직 수정

---

src/modules/events/dto/request/index.event.request.ts

이벤트 인덱스 업데이트 url 추가
<br><br>
<br><br>
<br><br>
SCRUM-242
<br><br>

feat: 이벤트 인덱스 업데이트 url 추가

---

src/modules/studyTeams/studyTeam.service.ts
src/modules/users/repository/user.repository.ts

<br><br>
<br><br>
<br><br>
SCRUM-240
<br><br>

fix: 스터디 승인/거절 알림 로직 수정

---

src/modules/projectTeams/projectTeam.service.ts

<br><br>
팀 조회 필터링 fullstack 추가
<br><br>
<br><br>
SCRUM-
<br><br>

fix: 팀 조회 필터링 fullstack 추가

---

src/modules/projectTeams/projectTeam.service.ts
src/modules/studyTeams/repository/studyTeam.repository.ts

<br><br>
스터디 조회수 증가 수정
<br><br>
<br><br>
SCRUM-
<br><br>

fix: 스터디 조회수 증가 수정

---

src/modules/projectTeams/dto/response/get.projectTeam.response.ts
src/modules/projectTeams/projectTeam.service.ts

<br><br>
프로젝트 상세조회시 userId, year 추가
<br><br>
<br><br>
SCRUM-
<br><br>

fix: 프로젝트 상세조회시 userId, year 추가

---

src/modules/projectTeams/projectTeam.service.ts

<br><br>
프로젝트 팀원 추가 로직 수정 - 팀원들 생성시간 기준으로 오름차순으로 정렬
<br><br>
<br><br>
SCRUM-245
<br><br>

fix: 프로젝트 팀원 추가 로직 수정

---

src/modules/bookmarks/repository/bookmark.repository.ts
src/modules/likes/repository/like.repository.ts
src/modules/projectTeams/dto/request/get.team.query.request.ts

이력서 좋아요/북마크 목록 조회 필터링 로직 수정
<br><br>
이력서 좋아요/북마크 목록 조회 시 일부 유저 정보가 안 나오는 문제를 해결했습니다.
<br><br>
<br><br>
SCRUM-255
<br><br>

fix: 이력서 좋아요/북마크 목록 조회 필터링 로직 수정

---

src/modules/resumes/dto/request/index.resume.request.ts

<br><br>
<br><br>
<br><br>
SCRUM-257
<br><br>

fix: 이력서 인덱스 기수,메인 포지션 추가

---

src/modules/resumes/dto/request/index.resume.request.ts
src/modules/sessions/dto/request/index.session.request.ts
src/modules/users/dto/request/index.user.request.ts

<br><br>
<br><br>
<br><br>
SCRUM-
<br><br>

fix: 기수 string으로 변환

---

.github/workflows/stage.yml

저희 서비스에 스테이징 서버 구축을 완료 했습니다
<br><br>
- staging.yml 생성
- ci.yml 수정
<br><br>
- 이제 배포를 할때 develop브랜치로 먼저 머지를 해주세요.
- develop브랜치로 머지를 하시면 스테이징 서버에 배포가 됩니다.
- 그 이후 괜찮으면 메인으로 머지를 해주세요!
<br><br>
BACKEND-2
<br><br>

add staging server

---

.github/workflows/ci.yml
.github/workflows/stage.yml

- 오타 고침
<br><br>
<br><br>
<br><br>
SCRUM-
<br><br>

fix: typo on environment
